# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix: # don't test osx + r-devel
  include:
  - os: linux
    r: release
    dist: bionic
  - os: linux
    r: devel
    dist: bionic
  - os: osx
    r: release
  - os: osx
    r: oldrel

r_github_packages:
  - r-lib/covr

after_success:
    - Rscript -e 'covr::codecov()'